name: We Love That Place
favicon: null
layout_spectrum: 0.93959
typography_spectrum: 0.7152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#b4c7ca'
    - '#05449c'
    - '#09120b'
    - '#53505c'
  brandStrength: 0.3518557418137789
  lightness: 0.17025316110812128
  saturation: 0.5656468640081584
  rhythmicContrast: 0.5957295002881438
purpose: []
